
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ID LPAREN NEWLINE NUMBER PLUS PRINT RPAREN\n    statements : statement\n               | statements statement\n    statement : ID EQUALS expression NEWLINEstatement : ID LPAREN expression RPAREN NEWLINE\n    expression : expression PLUS term\n               | term\n    term : NUMBERterm : IDempty :'
    
_lr_action_items = {'ID':([0,1,2,4,5,6,12,13,16,],[3,3,-1,-2,7,7,-3,7,-4,]),'$end':([1,2,4,12,16,],[0,-1,-2,-3,-4,]),'EQUALS':([3,],[5,]),'LPAREN':([3,],[6,]),'NUMBER':([5,6,13,],[10,10,10,]),'NEWLINE':([7,8,9,10,14,15,],[-8,12,-6,-7,16,-5,]),'PLUS':([7,8,9,10,11,15,],[-8,13,-6,-7,13,-5,]),'RPAREN':([7,9,10,11,15,],[-8,-6,-7,14,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,4,]),'expression':([5,6,],[8,11,]),'term':([5,6,13,],[9,9,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statement','statements',1,'p_statements','main.py',40),
  ('statements -> statements statement','statements',2,'p_statements','main.py',41),
  ('statement -> ID EQUALS expression NEWLINE','statement',4,'p_statement_assign','main.py',49),
  ('statement -> ID LPAREN expression RPAREN NEWLINE','statement',5,'p_statement_print','main.py',53),
  ('expression -> expression PLUS term','expression',3,'p_expression_binop','main.py',58),
  ('expression -> term','expression',1,'p_expression_binop','main.py',59),
  ('term -> NUMBER','term',1,'p_term_number','main.py',67),
  ('term -> ID','term',1,'p_term_id','main.py',71),
  ('empty -> <empty>','empty',0,'p_empty','main.py',82),
]
